[database]
url = "ratabase"
username = "rooser"
password = "roosword"
host = "localhost"
port = 5432
max_connections = 5

[server]
host = "127.0.0.1"
port = 8080

[rate_limit]
requests_per_second = 50
burst_size = 3

[log]
level = "info"
file = "logs/app.log"